// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzv3o7W1qb2DnDeNfZ6ctv1tTQleJbGu8',
    appId: '1:434024395068:web:fe2f0fb2fb43d77cce2e39',
    messagingSenderId: '434024395068',
    projectId: 'travel-app-7ff26',
    authDomain: 'travel-app-7ff26.firebaseapp.com',
    storageBucket: 'travel-app-7ff26.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2jZ8vDEbpQOnSXeJCi2kOaCzsHP_O4GA',
    appId: '1:434024395068:android:619d069d6b361742ce2e39',
    messagingSenderId: '434024395068',
    projectId: 'travel-app-7ff26',
    storageBucket: 'travel-app-7ff26.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvK9aNDcDGwOgkANXnpqW51h0RohvPIrM',
    appId: '1:434024395068:ios:70cd6a15040e2a21ce2e39',
    messagingSenderId: '434024395068',
    projectId: 'travel-app-7ff26',
    storageBucket: 'travel-app-7ff26.appspot.com',
    iosClientId: '434024395068-cirak4nds3c1boa4tl4dr2d8n15eg3ib.apps.googleusercontent.com',
    iosBundleId: 'com.example.travelApp',
  );
}
